### PR TITLE
reorganize PT page

### PR DESCRIPTION
**Pull request by mfsilva22**
I think this organization has a better flow (introduce concepts first, then use them in following text).

### CODE REVIEW

**Review by mwest1066 — APPROVED** [review]
The thing I liked about the old order was that it made at least some attempt to explain "what is PT" at the top. Maybe we need a section somewhere towards the top titled "What is PrairieTest?"

I'm approving this PR as is.

**Review by nwalters512 — APPROVED** [review]
I agree with Matt; jumping straight into value propositions without even 1 or 2 sentences about what PrairieTest is feels wrong.

I feel like the image under "Powerful exam management system" is out of place and the ideas behind it would be better communicated via plain text (either in the form of, or in addition to, some hypothetical "what is PT" text at the top of the page).

Like Matt, I'll rubber stamp this so you can merge it if you think this PR is still an improvement in its current form.

**Comment by mfsilva22** [comment]
I will try to add some text. I believe the image/diagram was a request by Matt, instead of using a block of text to convey that idea. If the next update is not an improvement, we will close this PR and keep the current version, until we have time to get something better.

**Comment by mfsilva22** [comment]
actually, changed my mind, it is not worth it trying to get this marginal improvement at this moment. I will close this PR now and keep the current version.

**Pull request closed without merging**
